parser: babel-eslint
extends:
  - eslint:recommended
  - plugin:react/recommended
  - airbnb
plugins:
  - react
  - jest
rules:
  no-use-before-define: 0
env:
  browser: true
  es6: true
  node: true
globals:
  jsdom: false
