FROM node:latest

WORKDIR /usr/src/app
RUN npm i lerna -g --loglevel notice
COPY package.json .
RUN npm install --loglevel notice

COPY packages/firstcut-marketplace ./packages/firstcut-marketplace

COPY lerna.json .
RUN lerna bootstrap

CMD [ "npm", "--prefix", "packages/firstcut-marketplace", "start" ]
