FROM node:11.2.0
WORKDIR /usr/app

COPY package.json .
RUN npm install -g lerna react-scripts yarn gulp
COPY . .

RUN echo y | lerna clean && npm run build:babel && lerna bootstrap
EXPOSE 3000
CMD npm run run:client
