version: '2'
services:
  client:
    build: .
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    command: npm run run:marketplace
    ports:
      - "3000:3000"
    env_file:
      - dev.env
  server:
    build: .
    command: meteor run --settings settings.json
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
      - /usr/app/packages/firstcut-marketplace-server
    ports:
      - "3000:3000"
    env_file:
      - dev.env
